spring:
  # Vault
  cloud:
    vault:
      scheme: http
      host: 127.0.0.1
      port: 8200
      token: hvs.R569qScTjj2SGGGt8Hzog59U # import your token vault in here
  config:
    import: vault://

  # Database Configuration
  datasource:
    port: 3306  # MySQL default port
    schema: eng_dev  # Database schema name
    hikari:
      connectionTimeout: 20000  # Maximum wait time for a connection (in ms)
      maximum-pool-size: 5  # Max number of connections in the pool
    url: jdbc:mysql://localhost:${spring.datasource.port}/${spring.datasource.schema}  # JDBC URL
    username: ${secret-mysql-username}  # Database username
    password: ${secret-mysql-password}  # Database password
  jpa:
    show-sql: true

  # WebSocket Configuration
  websocket:
    allowed-origins: http://localhost:4200  # Allowed WebSocket origins
    message-size-limit: 128KB  # Maximum message size
    send-timeout: 5000  # Send timeout in milliseconds
    send-buffer-size-limit: 512KB  # Send buffer size limit
    time-to-first-message: 20000  # Time to first message in milliseconds

  # Flyway Database Migration
  flyway:
    url: jdbc:mysql://localhost:${spring.datasource.port}/  # Flyway migration base URL
    schemas: ${spring.datasource.schema}  # Flyway migration schema
    user: ${spring.datasource.username}  # Uses the same database username
    password: ${spring.datasource.password}  # Uses the same database password
    enabled: true  # Enables Flyway for automatic migration
    validate-migration-naming: true  # Ensures migration files follow correct naming conventions

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${custom.security.oauth2Url}  # OAuth2 issuer URL
            
  # Redis Configuration
  redis:
    host: localhost  # Redis server hostname or IP address
    port: 6379       # Redis server port (default is 6379)
    database: 0      # Redis database index (default is 0, but you can configure it for multiple databases)
    timeout: 5000    # Connection timeout in milliseconds (5 seconds here)
    lettuce: # Lettuce is the Redis client used for communication
      pool: # Connection pool settings for managing Redis connections
        max-active: 8  # Maximum number of active Redis connections in the pool
        max-idle: 8    # Maximum number of idle connections in the pool (unused connections)
        min-idle: 0    # Minimum number of idle connections in the pool (connections that are ready to use)
        max-wait: -1   # Maximum time to wait (in milliseconds) for an available connection. -1 means unlimited wait time

# Application Metadata
info:
  app:
    name: "Prime Project"  # Application name
    description: "Prime backend project for development"  # Short description
    version: "1.0.0"  # Current application version

# Custom Configuration
custom:
  user:
    url: http://localhost:8070  # Custom user service URL
  security:
    clientId: admin  # OAuth2 client ID
    clientSecret: password  # OAuth2 client secret (consider using environment variables for security)
    oauth2Url: http://localhost:8070  # OAuth2 authentication server URL

# Eureka Service Discovery Configuration
eureka:
  preferIdAddress: true  # Prefer instance ID address for service resolution
  client:
    fetchRegistry: true  # Enables fetching the registry from Eureka
    registerWithEureka: true  # Registers this service with Eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL