ALTER TABLE `user`
ADD COLUMN `google_id` VARCHAR(255),
ADD COLUMN `first_name` VARCHAR(255),
ADD COLUMN `last_name` VARCHAR(255),
ADD COLUMN `full_name` VARCHAR(255),
ADD COLUMN `picture` TEXT,
ADD COLUMN `is_email_verified` BOOLEAN DEFAULT FALSE,
ADD COLUMN `is_active` BOOLEAN DEFAULT TRUE;